### ISSUE TITLE
The app crashes while I select a color

### ISSUE THREAD

**Issue by canesardo04** [ImpulseAdventure/GUIslice-Builder#110]
[20200905_185044.txt](https://github.com/ImpulseAdventure/GUIslice/files/5178388/20200905_185044.txt)
this is the log.
i don't know how to do it everytime i try to select a color for anything as a background or change the color of an object in the gui application crashes and tells me "a fatal error has occurred"

**Comment by ImpulseAdventure** [comment]
Hi @canesardo04 — to help narrow down the issue, can you:
- Confirm which Builder version you are running
- Ideally, attach the Builder project to this issue as well

Thanks

**Comment by canesardo04** [comment]
i use GuiSliceBuilder 0.15.b004 
I have already tried to reinstall but nothing, there is no specific project in which this bug happens but it happens in all projects and in addition the .bat don't open the program but I had to go to the lib folder and open the .jar file

**Comment by Pconti31** [comment]
@canesardo04 Seems you were not using GUIslice.bat ot GUIslice.sh and instead running the jar file directly.
That would cause all sorts of crashes because in that case the Builder can't find GUIsliceBuilder/templates folder and it needs its contents.  In this case you simply need to move the jar file up one folder and then you can run the Builder without problems.  We do this with the macos install.
I would have answered you quickly had you simply posted your additional information here instead of communicating by github email which I rarely read.  
Paul--
