### ISSUE TITLE
Builder not launching

### ISSUE THREAD

**Issue by bajoP** [ImpulseAdventure/GUIslice-Builder#119]
When i try opening the app it crashes, i saw cmd open up and close for a short time and nothing happens afterwards

1. Install
2. Open
3. wait for the cmd to open for a short period of time ( less then a second)

**Expected behavior**
Open the app

**Crash log / Project files**
I dont get any

- Builder version: tried 3 of the latest ones 
- OS: Windows 10

**Additional context**

**Comment by Pconti31** [comment]
@bajoP First did you use the installer?  
I log everything in the builder so if the folder GUIsliceBuilder/logs is empty then it
sounds like the environment variable JAVE_HOME isn't set correctly.

anyway, open a terminal cmd window using cmd.exe
first enter 
```
echo %JAVE_HOME%
```
In my case this is C:\jdk1.8.0_192
if you are reusing Arduino's IDE Java than it would be something like
C:\Program Files (x86)\Arduino\java
If that looks ok enter
```
%JAVA_HOME%\bin\java -version
```
You should get something like
```
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)
```
If you read our wiki for the installation you will note we require Java 1.8 not any higher although I have used it with Java 11 without issue.

If all of this is good then cd to the GUIsliceBuilder installation folder for example:
```
cd C:\Program Files (x86)\GUIsliceBuilder
```
then try running the Builder directly using this command
```
%JAVA_HOME%\bin\java -jar lib\builder-0.15.b005.jar
```
assuming you are using 0.15.b005 otherwise look inside the lib folder for the full name of the jar file.
now just check for whatever error is reported.

**Comment by bajoP** [comment]
Fixed it by reinstalling arduino, ty for your help
