### ISSUE TITLE
Add Open Sketch Button

### ISSUE THREAD

**Issue by DonpK** [ImpulseAdventure/GUIslice-Builder#124]
**Describe the solution you'd like**
When the Generate Code button is pressed, automatically close the current Sketch, if open, and re-open the updated Sketch. 

**Additional context**
Currently, when Builder is used to edit or add display elements, the Generate Code button is pressed to save the changes to the existing Sketch code.  The user then needs to close the existing instance of the sketch if it's open, find the .ino file in Explorer and reopen the file. In a typical Builder work session these file operations might be done numerous times. These operations could be added to the Generate Code button or to a separate Close/Reopen button.

**Comment by ImpulseAdventure** [comment]
Hi Don —

Was the request to have the Builder close the old generated sketch in the Arduino IDE? If so, I don’t believe an application (such as the Builder) would have an ability to trigger such an action in a different application (IDE), other than an “open”.

**Comment by DonpK** [comment]
Hi Cal,

My thought was that Builder would both close the Arduino IDE running the sketch, if it was open, and reopen it when the new Builder code was loaded. However, I understand what you're saying, it might not be possible to have one app close another. Having the Generate Code button reopen the updated sketch might be useful if it's possible and not difficult to achieve.

**Comment by Pconti31** [comment]
@DonpK I'm sorry. but as much as that would be great I have never figured out a way to make this work.  A further complication is trying to starting/stopping programs from Java requires native support on each target platform, Windows 10, Linux, and Macs (which I don't own so that support is already hard).  Notepad++ text editor will detect that changes to files have occurred and ask if you want to reload them.  It would be nice if Arduino IDE  would do the same.
Paul--
