### ISSUE TITLE
Add Top/Bot text alignment fields for Text Button

### ISSUE THREAD

**Issue by farfarfromhome** [ImpulseAdventure/GUIslice-Builder#127]
Current the builder does not have the selection fields for TOP/BOT text alignment however GUIslice has the capability.  To currently use gslc_ElemSetTxtAlign() needs to be manually edited/added to the applicable elements in xxx_GSLC.h which becomes laborious when performing many development iterations.

If time is at a premium, a first pass where the fields can be added in the Builder without actually aligning the text in the Builder would be very helpful.

**Comment by Pconti31** [comment]
@farfarfromhome Sorry, but this makes no sense to me.  IMHO, GUIslice API only supports TOP and BOTTOM  because if you are laying out a GUI text fields by hand you have no idea how to judge the size and shape of your text within its boundary box.  

In the Builder you can move your text up and down pixel by pixel by using ALT -UP or Down Arrow keys.
   
If you can produce and post a test case that can't work by simply moving the text field up or down I'll reconsider.

The current 015.0 Builder has a small problem sizing text exactly but this is fixed in 0.16.0 by actually running the target platforms fonts in Java giving the exact display you will see on your target TFT Screen. Also, this release will add margin to text fields but this is really only needed for text input fields since you can't control placement easily otherwise
Paul--

**Comment by Pconti31** [comment]
@farfarfromhome I just noticed you had made a similar request to GUIslice API for this for Text Buttons which makes more sense to me.  So I have reconsidered this and will investigate for all text fields and will mark this as request for enhancement #195.
Paul--

**Comment by farfarfromhome** [comment]
@Pconti31 

I apologize for not being clear.  It is indeed needed for the text button, not for the general text element.

**Comment by Pconti31** [comment]
Fixed in Release 0.16.0
