### ISSUE TITLE
How to add umlaut to a text label

### ISSUE THREAD

**Issue by daybyter** [ImpulseAdventure/GUIslice-Builder#148]
Trying to add an german umlaut to a text label, but it seems they are missing from the character map, although I enable utf-8 ?

- Add a label to a page
- Open the properties of the label
- Double click on the text and try to add an umlaut
- Open the character map via right click and umlauts are missing?

**Comment by Pconti31** [comment]
First UTF8 only works with TrueType fonts.  All other fonts are 7 bit or 8 bit ascii.  TrueType fonts are only available with the SDA driver using linux as the target platform.   I did just add NotoLatin1 font which is 8 bit ascii and might have what you want.  Otherwise you will need to create your own fonts.

If you want the NotoLatin1 you will need to copy the NotoLarin1 fonts to your Arduino library/Adafruit_GFX/fonts folder before using the Arduino IDE.

Paul--

**Comment by daybyter** [comment]
Thanks a lot for your response. So creating a font seems to be the way to go. So I am looking for pointers on how to do this and this was my first find:

https://learn.adafruit.com/creating-custom-symbol-font-for-adafruit-gfx-library

**Comment by daybyter** [comment]
Found more stuff:

https://rop.nl/truetype2gfx/

https://www.foobarflies.io/adafruit-gfx-font-customiser/

https://blog.squix.org/2016/10/font-creator-now-creates-adafruit-gfx-fonts.html

Especially the first link seems to provide a rather convenient way to create fonts...have to check further

**Comment by Pconti31** [comment]
@daybyter You can also use my tool, ttf2gfx.
It's how I created NotoLatin1
[ttf2gfx](https://github.com/Pconti31/TTF2GFX)
Paul--

**Comment by Pconti31** [comment]
I'm closing this topic since it seems you have the information you need.
Any problem feel free to open a new issue.
Paul--
