### ISSUE TITLE
GUIslice Builder crash when changing Minimum Value at Ramp Gauge

### ISSUE THREAD

**Issue by u1550l** [ImpulseAdventure/GUIslice-Builder#184]
**Describe the bug**
Changing Minimum Value on a  Ramp Gauge element is not possible. Builder crashes immediately.

**To Reproduce**
1. add a Ramp Gauge to a page
2. change "Minimum Value" to 10 in Property View, press Enter
3. GuisliceBuilder will crash
4. crash log attached

**Expected behavior**
Minimum Value property should take argument.

**Crash log / Project files**
no .prj file exisiting.
Bug occurs on an empty (new) project as well as on an well working.
[20220204_111930.txt](https://github.com/ImpulseAdventure/GUIslice-Builder/files/8001992/20220204_111930.txt)
[20220204_111926.txt](https://github.com/ImpulseAdventure/GUIslice-Builder/files/8001994/20220204_111926.txt)

**Screenshots**
![04-02-2022 11-20-23](https://user-images.githubusercontent.com/31414083/152512684-d23c02fe-78b1-4ace-8a19-170f25053a9c.jpg)

**Version**
- Builder version: GUIslice Builder ver: 0.17.b02
- OS: Windows 10

**Additional context**

**Comment by Pconti31** [comment]
@u1550l Ok, You can now download Release 0.17.b04 for the fix.
Note that I'm only trying to give you an idea of what the gauge will look like  so I show it at about maximum value not its starting value since that could be 0 and then nothing would show up on screen.  Also, since I'm color blind the colors could be off a bit.

Paul--

**Comment by u1550l** [comment]
@Pconti31: seems to work. Thx! - Richard
