### ISSUE TITLE
Guislice-Builder don't bring German Umlauts.

### ISSUE THREAD

**Issue by umsmin** [ImpulseAdventure/GUIslice-Builder#228]
**Describe the bug**
My Guislice-Builder 0.17.b18 and also the older one show me the text with German umlaut. I use Arial Fonts with full size off 0xFF. But when he generate the code something goes wrong. I write `Gerät :` and he make `Ger\xe4t :`
He also don't care of setting the flag on UTF-8 or not. After I change it manually in the _GLSC.h file all be well.

Here is one from the fonts:

[arial10pt8b.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/10221054/arial10pt8b.zip)

**To Reproduce**
In any kind he make this.

**Expected behavior**
He don't change the umlauts as they are.

**Version**
- Builder version: 0.17.b18
- OS: Windows 10

**Comment by Pconti31** [comment]
@umsmin For me to help people I need a sample project not just a font.  Please put together a small project with just the single text field you want to display so I can look at the *.prj and *.ino and *_GSLCS.h files to see what is going on or debug if necessary.
Thanks.

**Comment by umsmin** [comment]
No problem here a small example:

[Umlaute.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/10228443/Umlaute.zip)

Uli

**Comment by umsmin** [comment]
Thanks for your help. But one thing I don't understand. When I change this `Ger\xe4te :` to `Geräte :` later in the sketch it works without your patch.  
```
// Create E_ELEM_TEXT1 text label
  pElemRef = gslc_ElemCreateTxt(&m_gui,E_ELEM_TEXT1,E_PG_MAIN,(gslc_tsRect){0,10,296,17},
    (char*)"Ger\xe4t H\xf6rnchen Gem\xfcse",0,E_ARIAL10PT8B);
  gslc_ElemSetFillEn(&m_gui,pElemRef,false);
```
I change to:

```
// Create E_ELEM_TEXT1 text label
  pElemRef = gslc_ElemCreateTxt(&m_gui,E_ELEM_TEXT1,E_PG_MAIN,(gslc_tsRect){0,10,296,17},
    (char*)"Gerät Hörnchen Gemüse",0,E_ARIAL10PT8B);
  gslc_ElemSetFillEn(&m_gui,pElemRef,false);
```

The screen show:

`Gerät Hörnchen Gemüse`

Without any problems. 

My font is converted with the tool from Adafruit. I use it on one of my Linux Servers and it works well. 

I've made the option 3 and patched the library from Bodmer and it works without editing later the code made from Guislice-Builder it's okay but not nice. For me normally no need for any part of Software or library to translate my words written in Guislice-Builder. 

Sorry for my stupid questions but I am 60 and not one from the young generation born with a mobile in the hands. 

Uli

**Comment by Pconti31** [comment]
@umsmin We seem to over lapped messages.
Rather than patching TFT_eSPI I found a simple work-around.
Edit your Umlaute.ino file and inside the setup() function after InitGUIslice_gen() add these lines
Inside your

  // find our display driver
  TFT_eSPI* tft = (TFT_eSPI*)gslc_GetDriverDisp(&m_gui);
  // turn off UTF8 support to use GFX fonts with TFT_eSPI
  tft->setAttribute(UTF8_SWITCH, false);
This will turn off decodeUTF8() and allow GFX characters greater than 127 to display.
Paul--

**Comment by Pconti31** [comment]
@umsmin My the way, you are much younger than me!  I wish I was in my 60s again...
Paul--

**Comment by umsmin** [comment]
@Pconti31 Yeah but you take this thing with - in Germany we say - `Du hast es mit der Muttermilch getrunken`

For me the the additional code 

```
 // find our display driver
  TFT_eSPI* tft = (TFT_eSPI*)gslc_GetDriverDisp(&m_gui);
  // turn off UTF8 support to use GFX fonts with TFT_eSPI
  tft->setAttribute(UTF8_SWITCH, false);
```

Works without this patch. It's not good but okay.

Thanks 

Uli

**Comment by Pconti31** [comment]
@umsmin The reason changing your literal string by inserting "ü" directly is because you are inserting the unicode 16 bit character from your keyboard thus you get the literal string "\x00\xfc" in binary while if you use the builder I output the correct binary code for GFX fonts simply "\fc".

Bodmers decodeUTF8() routine detects the  "\x00\xfc" as a 16 bit unicode thanks to the "\x00" trigger and simply outputs the next character it finds which is the "\xfc" from your font.

While this works I 'm not sure I do the same outputting "\x00\xfc" and not break Adafruit-GFX library.  I plan on looking into this though for a future release.
Paul--

**Comment by umsmin** [comment]
@Pconti31 After I changed it like you told me, only the new things I make in my project will be shown in the right way. The old ones I only changed UTF-8 from false to true don't shown in the right way. I don't want to make all new there.

Uli

**Comment by Pconti31** [comment]
@umsmin sorry I have lost track of what you are doing and what is working or not?  Can you create and zip a project that fails to show whatever?

**Comment by Pconti31** [comment]
@umsmin by the way unless your target is raspberry pi the utf8 property is completely ignored by guislice and not passed on to any graphics library.

**Comment by umsmin** [comment]
I don't use raspberry pi. It works on esp32. Tomorrow I will send you the project

**Comment by Pconti31** [comment]
@umsmin Release 0.17.b19 I think will solve your problem with extended character sets without needing to use 
```
 tft->setAttribute(UTF8_SWITCH, false);
```
in your *.ino file.  Please let me know if this works out for you.
Paul--

**Comment by Pconti31** [comment]
@umsmin Since I haven't heard from you since dec 14, 2022 I'll just close this issue.
If you are still having problems and you suppliy additional information I'll reopen this case.
