### ISSUE TITLE
Builder cannot be instructed not to overwrite existing files

### ISSUE THREAD

**Issue by tfischer4765** [ImpulseAdventure/GUIslice-Builder#232]
Example to illustrate the problem: On more advanced problems, the generated platformio.ini generally does not work. With every code generation, the (non-working) platformio.ini will be regenerated. Currently the only known workaround is to restore the user's own working platformio.ini from git.

it would be preferrable if the code generation had some tuning options that allow the user to indicate he does or does not want to have certain files regenerated. For each given file the options "leave alone", "update" and "force generation" would be ideal, though force isn't strictly necessary to solve the problem and would be considered a convenience.

**Comment by Pconti31** [comment]
@eastWillow I have built and tested Release 0.17.b21 so that if you add your custom platformio.ini file to GUIsliceBuilder/templates/PlatformIO_Custom it will be used when creasting new platformio projects.
The Builder has also been modified to no longer overwrite an existing platformio.ini file.  
You can also edit platformio enviroment templates inside templates/PlatformIO_Config such as Arduino-HX8357-FT6206.txt and copy them to PlatformIO_Custom to avoid creating one platformio.ini file.  This of would be it easier to support projects containing different MCUs and Displays.
Paul--
