### ISSUE TITLE
Strange codes in generated file

### ISSUE THREAD

**Issue by Kabron287** [ImpulseAdventure/GUIslice-Builder#257]
**Describe the bug**
Example: 
**ex25_bld_popup.prj**
**To Reproduce**
1. Generate

**Expected behavior**
In file:  **ex25_bld_popup_GSLC.h**
@ line 42: **#define                           "/"**
@ line 144:   **gslc_SetBkgndImage(&m_gui,,));**

**Version**
- Builder version: **builder-win-x64-0.17.b27**
- OS: **Windows 10 x64**

**Comment by Pconti31** [comment]
@Kabron287 Sorry, but I just tried this and everything worked fine.
Maybe you played around with the options.
Look at the E_PROJECT_OPTIONS posted below and see what it should look like.

![popup](https://github.com/ImpulseAdventure/GUIslice-Builder/assets/44075106/d8a4e4e3-067b-480d-956f-0434adafea27)

If you can't see whats wrong post a full zip file starting with the folder ex25_bld_popup
Paul--

**Comment by Kabron287** [comment]
Here is my project
[ex25_bld_popup.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/15217571/ex25_bld_popup.zip)

**Comment by Kabron287** [comment]
Errors are allready in Builder templates: graphics.t, linux.t

  // Set Background to an image
  gslc_SetBkgndImage(&m_gui,$<IMG-109>$<IMG-101>,$<IMG-102>));

**Comment by Pconti31** [comment]
@Kabron287 I would like to help you out here but no luck.
So I'll point out a few things here.
- Your choice of GUIslice_config.h include has nothing to do with code generation.  It does of course have a great effect on your compiles and links with Arduino IDE or PlatformIO.
- The project file in your zip was set to Adfruit_GFX, why when you are clearly using TFT_eSPI I guess because you didn't save the project but the builder won't do a code generation without a save if you changed Adfruit_GFX to TFT_eSPI so I'm confused here.
- My graphics.t file has the macro
```
<BACKGROUND_IMAGE>
  
  // Set Background to an image
  gslc_SetBkgndImage(&m_gui,$<IMG-109>$<IMG-101>,$<IMG-102>));
<STOP>
```
which is correct and won't even be used unless you choose to use a background image by edit of E_PROJECT_OPTIONS
- Finally here is a screen shot after I did as you asked above, set driver to TFT_eSPI, code generation.
Modified my GUIslice_config.h to use esp-tftespi-default-ft6206.h then complied using ArduinoIDE
![ide](https://github.com/ImpulseAdventure/GUIslice-Builder/assets/44075106/54827078-586a-4319-89dc-22275982a43f)

I can't think of anything else I can do...

Paul--

**Comment by Pconti31** [comment]
@Kabron287 I take point two above back.  Seems there is a bug that allows generation after making changes to E_PROJECT_OPTIONS without doing a save.  I'll fix that in a future release.

**Comment by Kabron287** [comment]
@Pconti31
you right, my proj had different settings in E_PROJECT_OPTIONS and Edit->Options. That was the source of errors.

Why these setting are located in 2 different places? Why not to join them in one place?

**Comment by Kabron287** [comment]
Closed

**Comment by Pconti31** [comment]
@Kabron287 Why two places?  Well, for good or bad my thinking is that not everyone uses Adadfruit_GFX and a 320 x 240 screen right?  So, why have them enter these values everytime they create a new project.  The edit->options values are stored in user prefences not the *.prj file and are used as starting values for new projects but if you need to override them for a one off project you just edit the E_PROJECT_OPTIONS and they will be stored inside the *.prj file. 

Also, say you start with Arduino Mega and move on to an ESP32 but decide to go back and make some small changes to your old mega project.  Well, the E_PROJECT_OPTIONS are stored inside the *.prj file so you don't need to override them in that case since the project file just remembers the settings.  

Still, I agree it has caused a bit of confusion.   Maybe I could instead not only save E_PROJECT_OPTIONS in the current *.prj file but also place the new edits inside user prefences and get rid of edit->options altogether...
Still, that would be a fair amount of work.   It would be nice if someone else took an interest like @etet100 has and help implement new features.  I'm in my seventies after all.

Paul--
