### ISSUE TITLE
Code Generation Failed

### ISSUE THREAD

**Issue by notascooby** [ImpulseAdventure/GUIslice-Builder#32]
Firstly great new version
I have an issue as follows:
Code generation fails for a project developed many versions ago.
Have tried ver 0.13.0.1 , 0.13.0.2 & 0.13.0.3.
Failure message generated is "CodeGenException :file:" the file path followed by "is corrupted missing tag ://<Startup !Start!>
Builder is installed in Windows 10 64bit computer
Any help would be appreciated.

**Comment by Pconti31** [comment]
To debug this I need you to post a zip file of the project folder including the *.prj and *.ino or*.c and
*.ino.bak.   
  Now even if you post your zip file of the project I may or may not be able to fix the issue but you should be able to move forward.   After creating your zip file just rename the .ino and .ino.bak to
something unique so you can pull out any custom edits you have made.  for example, name your .ino file .ino.orig .  The error you are gettng is due to missing tags in your *.ino file.  Now that you have renamed it a new fresh version will be created for you when you do the code gen.  
  Any custom code you have created will need to be cut and pasted from your saved .ino.orig file.
Paul--

**Comment by notascooby** [comment]
Added the two tags as you suggested and all worked correctly - thanks
This may not be important for the future development of Builder, but I also tried deleting the .ino & .ino.bak files however after selecting code generation the builder displayed a message that a log file had been created and then closed down.
I have closed issue - Thanks again

**Comment by Pconti31** [comment]
@notascooby any chance you could post the crash file?
It should be inside your GUIsliceBuilder\logs folder.

Paul--

**Comment by DonpK** [comment]
I have been getting the same error on a new sketch before any GUIslice code has been added. I'm using Builder 0.13.b009.  I am using a newly setup Windows 10 64 bit computer so the problem may be associated with the change. Previous versions of GUIslice/Builder worked fine on a Windows 7 PC. I copied the Arduino\libraries folder from the Win 7 PC,, but have done fresh installs of the latest GUIslice/Builder versions on the Win 10 PC.

[Test2.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/3964406/Test2.zip)

**Comment by Pconti31** [comment]
The problem here is that test2.ino WAS NOT created by the builder.
Delete Test2.ino, keep Test2.prj and re-run the builder and do a code gen than you will have a 
valid test2.ino file.
When you create a new project file and no .ino or .c for linux file exists the Builder
creates a valid .ino file by creating a new .ino file with the contents of 
GUIsliceBuilder\templates\ino.t  creating it for the first time.  
After that you can edit the new .ino file and the builder will correctly update it as long as you don't delete any of the //<XXXX !Start!> and  //<XXXX !END!> lines the builder needs to find the the various code sections for new code insertions.   
This is all discussed inside the user guide.
Paul.

**Comment by DonpK** [comment]
Thanks!
    Don
