### ISSUE TITLE
Code generation failed when any text of '$' followed by any alphabet

### ISSUE THREAD

**Issue by knyipab** [ImpulseAdventure/GUIslice-Builder#46]
To reproduce the bug, just add a text or any element that has text property and then put in '$A'. Press "Code Generation" and then get error message pop up. It seems that it's because dollar sign '$' is used as an identifier for code generation in template files.

**Comment by Pconti31** [comment]
assigned bug 123.  will be fixed in 0.13.b010.
Turns out to be a bug inside java 8's util.regex.Matcher.appendReplacement() when the replacement string contained a '$' anywhere in it.   Fixed by simply never giving a string to this routine (I give it an empty string "" now) and simply doing a separate string append.

**Comment by Pconti31** [comment]
fixed in release 0.13.b010
