### ISSUE TITLE
Any code generation for text input or number input failed with 0.13.b009

### ISSUE THREAD

**Issue by knyipab** [ImpulseAdventure/GUIslice-Builder#48]
Code generation for projects with text input and number input works just fine in v0.13.0.3. After I installed 0.13.b009, it failed with a pop up window saying "Code Generation Failed: builder.codegen.CodeGenException: java.lang.IllegalArgumentException: Illegal group reference". Btw, I'm using Windows 10. 

New a project, save it, new a text input, press code gen and then the bug happens. Here is an example project: 
[gui2.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/4012633/gui2.zip)

**Comment by Pconti31** [comment]
This is the same as bug 123 the failure is inside java.util.regex.Matcher.appendReplacement
and is already fixed in 0.13.b010 branch.  new release coming soon.
I've attached the output gui2.ino file for your information.
[gui2.zip](https://github.com/ImpulseAdventure/GUIslice-Builder/files/4012780/gui2.zip)
Paul--

**Comment by Pconti31** [comment]
Well issue 49 wasn't a duplicate so reopened it and I've assigned issue 49 to bug 126.
As to bug 125 I have fixed it and turns out the template should have had
$<COM-019> instead of $<KEY-019>.  Will be fixed in 0.13.b010
Paul--
