### ISSUE TITLE
Dragging of elements unaffected by change in screen size.

### ISSUE THREAD

**Issue by JohannesWilde** [ImpulseAdventure/GUIslice-Builder#93]
I just installed GUIslice-Builder under Linux [version 0.14.b004]. Changing the screen size in the E_PROJECT_OPTIONS via "TFT Screen Width" and "... Height" the screen area in E_PG_MAIN changes accordingly - however trying to drag elements in using these new dimension seems to use the default of 320x240 regardless.
I tried smaller [120x60] and bigger [480x320] dimensions - it seems to internally stay at 320x240.

**Comment by JohannesWilde** [comment]
Hm, if I go to Edit->Options->TFT Screen Width  / ...Height, then these values are used as [I] expected.

**Comment by Pconti31** [comment]
Yes, I found that there were a few places where General tab values were still being used instead of the project tab values.  One more extreme case is when you go from a larger screen in General tab  to a smaller screen in project tab.   You drop a new widget and you can't see it because it dropped beyond your new screen size. I have fixed these cases in the 0.14.b005 branch but can't release until Calvin finishes his review of fonts and the various display he supports.  Until then the work around is to also change values in your options->general tab.  It's a pain I know.  Sorry about that.
Paul--

**Comment by JohannesWilde** [comment]
No worries, just wanted to let you know.

**Comment by Pconti31** [comment]
Addressed in Release 0.15.0
