### ISSUE TITLE
[Feature Request] Add a program statement builder

### ISSUE THREAD

**Issue by Lucy2003** [ImpulseAdventure/GUIslice-Builder#95]
**Describe the solution you'd like**
It's not very easy for the beginner to read the API WIKI (Just like me).
Each function needs args that is not easy to remember even the function args is cut down by 0.14.0 update...

So,I think if it can add a [program statement builder] that can build some statement by GUI.Just like this:

![PSbuilder(Just a example)](https://user-images.githubusercontent.com/53362310/85690153-df761a00-b705-11ea-99ee-c713aac78534.PNG)

Thanks.

**Comment by Pconti31** [comment]
Usually these sort of things are handled by the text editor using code completion.   Arduino IDE 1.9 currently in beta is supposed to have this feature.  Of course, its been in beta for a long time and given that I just downloaded the current beta and it hung the moment I asked for code completion it seems to still have quite a way to go before shipping. :( 

Microsoft VSCODE does have code completion as does PlatformIO with vscode.  I'm not suggesting you go this way since its not for beginners but I thought I would show you an example of what it does.
Say I start typing:
![api_code](https://user-images.githubusercontent.com/44075106/85746824-c0ab5f80-b6d4-11ea-8381-38cf707447ff.png)
You see the choices available, then I select the api i want:
![api_args](https://user-images.githubusercontent.com/44075106/85747007-e8022c80-b6d4-11ea-8aa5-33a050e1f85a.png)
Now I see the list of arguments it takes and as I move through them one at a time I get a lists of possible variables that could be used as the argument:
![api_arg2](https://user-images.githubusercontent.com/44075106/85747202-12ec8080-b6d5-11ea-8a98-ba0d47921d74.png)

Hopefully, you can see that I can't add much value to all of this.  

Still I understand that having a way to bridge the gap between the API documents, API examples and the wiki would be nice.  Though I think that is more of Calvin's job since GUIslice API is his project.  

The point of the Builder is to shield as much as possible from beginners the API so they don't need to deal with it's complexity.  Only as they need more advanced features do they need to explore the API deeper.  Many people only need to deal with their Application code and a very small set of the API to put up  display values or grab input since the GUI is otherwise fully generated for them.  If the Builder could help with any further complexity  I'm open to making additions.  I'm just unsure of what needs to be added.  People such as yourself giving suggestions would be very useful.
Paul--

**Comment by Lucy2003** [comment]
I got it. Thank you very much!
